### ISSUE TITLE
Messages comes up in both chat.

### ISSUE THREAD

**Issue by magrrtt** [JavaGuy12/StaffChat#2]
[Server] INFO magrrtt: s
 [Server] INFO ... 11 more
 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_151]
 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_151]
 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_151]
 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
 [Server] INFO at me.itguy12.staffchat.Main.onPlayerChat(Main.java:56) ~[?:?]
 [Server] INFO at me.itguy12.staffchat.Main.staffChat(Main.java:96) ~[?:?]
 [Server] INFO Caused by: java.lang.NoSuchFieldError: ORB_PICKUP
 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1252) [spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1314) [spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:481) [spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-BT64-1.12.2.jar:git-Spigot-7754231-a3b3a42]
 [Server] INFO org.bukkit.event.EventException: null
 [Server] ERROR Could not pass event AsyncPlayerChatEvent to StaffChat v1.0.1
 [Server] INFO magrrtt issued server command: /sc

**Comment by Marfjeh** [comment]
Can confirm having this issue aswell.

**Comment by jacksoneshbaugh** [comment]
I cannot find this issue... did you download the latest plugin version?

**Comment by Marfjeh** [comment]
https://github.com/JavaGuy12/StaffChat/blob/22ac2ef03b1931a0674066c54ba4ef5a2b2003c6/src/me/itguy12/staffchat/Main.java#L96

this is broken in the latest spigot builds. after removing the line (yeah I know) it works correctly.
